### PR TITLE
Custom docker

### PR DESCRIPTION
**Pull request by JeffreyZh4ng**
Added Docker functionality to the backend that will accept a DockerHub repo link

### CODE REVIEW

**Comment by therishidesai** [comment]
fix merge conflicts

**Comment by ezhang887** [comment]
I think this should point to multi-node instead of master.

**Comment by apache8080** [comment]
It is pointing to multinode

**Comment by therishidesai** [comment]
lgtm! @Bo887  go ahead and merge it

**Comment by ezhang887** [comment]
Also, I think this depends on some commits in https://github.com/acm-uiuc/nvdocker/tree/hackillinois

**Pull request merged**
